### ISSUE TITLE
spike: working with remote endpoints

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/faucet#3]
https://github.com/ApeWorX/faucet/blob/99c7f7264ef546087dc77ad299b9c382d521bc1c/faucet/app.py#L21

Because of this line, I believe that it will only work with localhost providers. could this be refactored to work with remote endpoints or is this something a user should do?

**Comment by sabotagebeats** [comment]
@fubuloubu let me know your thoughts and if we should try to fix or if we should just let users fix this in their production environments?

**Comment by fubuloubu** [comment]
yeah, we definitely want to be able to have it work with a remote endpoint (e.g. another container or alchemy)

**Comment by sabotagebeats** [comment]
completed
